# Generated by Django 3.1.6 on 2021-03-23 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_agent',
            field=models.BooleanField(default=False),
        ),
    ]
