# Generated by Django 3.1.6 on 2021-03-25 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_userprofile_is_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='subscription_paid',
            field=models.BooleanField(default=False),
        ),
    ]
