# Generated by Django 3.1.6 on 2021-04-06 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_userprofile_subscription_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='psr_number',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
