# Generated by Django 3.1.6 on 2021-02-22 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_remove_product_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_listed', models.BooleanField(default=False)),
                ('is_spotlight', models.BooleanField(default=False)),
                ('full_name', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=256)),
                ('call_between_hrs', models.CharField(blank=True, max_length=256, null=True)),
                ('county', models.CharField(max_length=256)),
                ('area', models.CharField(max_length=256)),
                ('eircode', models.CharField(blank=True, max_length=256, null=True)),
                ('property_type', models.CharField(max_length=256)),
                ('selling_type', models.CharField(max_length=256)),
                ('price', models.IntegerField()),
                ('no_of_bedrooms', models.IntegerField()),
                ('no_of_bathrooms', models.IntegerField()),
                ('facilities', models.CharField(max_length=256)),
                ('floor_area', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ber_rating', models.CharField(max_length=256)),
                ('tax_designation', models.CharField(max_length=256)),
                ('top_features_1', models.CharField(blank=True, max_length=100, null=True)),
                ('top_features_2', models.CharField(blank=True, max_length=100, null=True)),
                ('top_features_3', models.CharField(blank=True, max_length=100, null=True)),
                ('top_features_4', models.CharField(blank=True, max_length=100, null=True)),
                ('top_features_5', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(max_length=256)),
                ('images', models.ImageField(upload_to='')),
                ('times_viewed', models.IntegerField()),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product')),
            ],
        ),
    ]
