# Generated by Django 3.1.6 on 2021-02-22 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='facilities',
        ),
        migrations.AddField(
            model_name='listing',
            name='facility_1',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='facility_2',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='facility_3',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='facility_4',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='facility_5',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='facility_6',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
