# Generated by Django 3.1.6 on 2021-02-22 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_auto_20210222_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='company_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='times_viewed',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
