# Generated by Django 3.1.6 on 2021-02-22 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_listing_listing_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='listing_number',
            field=models.CharField(editable=False, max_length=32, null=True),
        ),
    ]
