# Generated by Django 3.1.6 on 2021-02-22 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_auto_20210222_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='is_spotlight',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
