# Generated by Django 3.1.6 on 2021-02-23 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_listing_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='expiration_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
