# Generated by Django 3.1.6 on 2021-02-25 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_friendly_name'),
        ('listings', '0009_auto_20210223_1151'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Listing',
            new_name='SaleListing',
        ),
    ]
