# Generated by Django 3.1.6 on 2021-02-25 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_friendly_name'),
        ('listings', '0010_auto_20210225_1054'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentListing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_number', models.CharField(editable=False, max_length=32, null=True)),
                ('is_listed', models.BooleanField(default=False)),
                ('is_spotlight', models.BooleanField(blank=True, default=False)),
                ('company_name', models.CharField(blank=True, max_length=256, null=True)),
                ('full_name', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=256)),
                ('call_between_hrs', models.CharField(blank=True, max_length=256, null=True)),
                ('county', models.CharField(max_length=256)),
                ('area', models.CharField(max_length=256)),
                ('eircode', models.CharField(blank=True, max_length=256, null=True)),
                ('property_type', models.CharField(max_length=256)),
                ('rent_type', models.CharField(max_length=256)),
                ('available_from', models.DateField()),
                ('lease_term', models.IntegerField()),
                ('price', models.IntegerField()),
                ('no_of_single_bedrooms', models.IntegerField()),
                ('no_of_double_bedrooms', models.IntegerField()),
                ('no_of_twin_bedrooms', models.IntegerField()),
                ('no_of_bathrooms', models.IntegerField()),
                ('furnishing', models.CharField(max_length=256)),
                ('facility_1', models.CharField(blank=True, max_length=256, null=True)),
                ('facility_2', models.CharField(blank=True, max_length=256, null=True)),
                ('facility_3', models.CharField(blank=True, max_length=256, null=True)),
                ('facility_4', models.CharField(blank=True, max_length=256, null=True)),
                ('facility_5', models.CharField(blank=True, max_length=256, null=True)),
                ('facility_6', models.CharField(blank=True, max_length=256, null=True)),
                ('floor_area', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ber_rating', models.CharField(max_length=256)),
                ('description', models.TextField(max_length=1000)),
                ('images', models.ImageField(upload_to='')),
                ('times_viewed', models.IntegerField(blank=True, editable=False, null=True)),
                ('expiration_date', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product')),
            ],
        ),
    ]
