# Generated by Django 3.1.6 on 2021-02-25 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0011_rentlisting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentlisting',
            name='lease_term',
            field=models.CharField(max_length=256),
        ),
    ]
