# Generated by Django 3.1.6 on 2021-02-26 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0014_auto_20210226_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentlisting',
            name='price',
            field=models.CharField(max_length=256),
        ),
    ]
