# Generated by Django 3.1.6 on 2021-03-01 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0016_auto_20210226_1234'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleListingImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('listing', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='listings.salelisting')),
            ],
        ),
    ]
