# Generated by Django 3.1.6 on 2021-03-01 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0017_salelistingimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salelistingimage',
            name='listing',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='listingImages', to='listings.salelisting'),
        ),
    ]
