# Generated by Django 3.1.6 on 2021-03-01 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0018_auto_20210301_1417'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rentlisting',
            old_name='images',
            new_name='header_image',
        ),
        migrations.RenameField(
            model_name='salelisting',
            old_name='images',
            new_name='header_image',
        ),
        migrations.RenameField(
            model_name='salelistingimage',
            old_name='image',
            new_name='images',
        ),
    ]
