# Generated by Django 3.1.6 on 2021-03-10 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0021_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.AddField(
            model_name='rentlisting',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='salelisting',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
