# Generated by Django 3.1.6 on 2021-03-16 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0023_rentlisting_no_of_bedrooms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentlisting',
            name='no_of_bedrooms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salelisting',
            name='price',
            field=models.IntegerField(),
        ),
    ]
