# Generated by Django 3.1.6 on 2021-03-16 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0024_auto_20210316_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentlisting',
            name='price',
            field=models.IntegerField(),
        ),
    ]
