# Generated by Django 3.1.6 on 2021-03-23 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_userprofile_is_agent'),
        ('listings', '0026_auto_20210323_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentlisting',
            name='user_profile',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.userprofile'),
        ),
        migrations.AlterField(
            model_name='salelisting',
            name='user_profile',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.userprofile'),
        ),
    ]
