# Generated by Django 3.1.6 on 2021-03-23 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0028_auto_20210323_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentlisting',
            name='times_viewed',
            field=models.IntegerField(blank=True, default=0, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='salelisting',
            name='times_viewed',
            field=models.IntegerField(blank=True, default=0, editable=False, null=True),
        ),
    ]
