# Generated by Django 3.1.6 on 2021-03-24 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0029_auto_20210323_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentlisting',
            name='thumbnail_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='salelisting',
            name='thumbnail_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
