# Generated by Django 3.1.6 on 2021-03-25 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0031_auto_20210325_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentlisting',
            name='no_of_bathrooms',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='rentlisting',
            name='no_of_bedrooms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rentlisting',
            name='no_of_double_bedrooms',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='rentlisting',
            name='no_of_single_bedrooms',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='rentlisting',
            name='no_of_twin_bedrooms',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='rentlisting',
            name='price',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='salelisting',
            name='no_of_bathrooms',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='salelisting',
            name='no_of_bedrooms',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='salelisting',
            name='price',
            field=models.PositiveIntegerField(),
        ),
    ]
