# Generated by Django 3.1.6 on 2021-04-06 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0032_auto_20210325_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='salelisting',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
