# Generated by Django 3.1.6 on 2021-04-10 18:34

from django.db import migrations, models
import listings.models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0034_rentlisting_email_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salelisting',
            name='header_image',
            field=models.ImageField(upload_to=listings.models.path_and_rename),
        ),
    ]
