# Generated by Django 3.1.6 on 2021-04-10 19:00

from django.db import migrations, models
import listings.models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0035_auto_20210410_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentlisting',
            name='header_image',
            field=models.ImageField(upload_to=listings.models.path_and_rename),
        ),
        migrations.AlterField(
            model_name='rentlistingimage',
            name='images',
            field=models.ImageField(upload_to=listings.models.path_and_rename),
        ),
        migrations.AlterField(
            model_name='salelistingimage',
            name='images',
            field=models.ImageField(upload_to=listings.models.path_and_rename),
        ),
    ]
