# Generated by Django 3.1.6 on 2021-04-12 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0036_auto_20210410_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentlisting',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='salelisting',
            name='description',
            field=models.TextField(),
        ),
    ]
