# Generated by Django 3.1.6 on 2021-04-14 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0037_auto_20210412_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentlisting',
            name='ber_rating',
            field=models.ImageField(default=None, max_length=256, upload_to=''),
        ),
    ]
