# Generated by Django 3.1.6 on 2021-04-14 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0038_auto_20210414_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentlisting',
            name='ber_rating',
            field=models.CharField(default=None, max_length=256),
        ),
    ]
