# Generated by Django 3.1.6 on 2021-04-17 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0039_auto_20210414_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='salelisting',
            name='poa',
            field=models.BooleanField(default=False),
        ),
    ]
