# Generated by Django 3.1.6 on 2021-04-29 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0040_salelisting_poa'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentlisting',
            name='poa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rentlisting',
            name='top_features_1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rentlisting',
            name='top_features_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rentlisting',
            name='top_features_3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rentlisting',
            name='top_features_4',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rentlisting',
            name='top_features_5',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
