# Generated by Django 3.1.6 on 2021-04-29 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0041_auto_20210429_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentlisting',
            name='top_features_1',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='rentlisting',
            name='top_features_2',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='rentlisting',
            name='top_features_3',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='rentlisting',
            name='top_features_4',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='rentlisting',
            name='top_features_5',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='salelisting',
            name='top_features_1',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='salelisting',
            name='top_features_2',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='salelisting',
            name='top_features_3',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='salelisting',
            name='top_features_4',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='salelisting',
            name='top_features_5',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
