# Generated by Django 3.1.6 on 2021-05-14 10:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0042_auto_20210429_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentlisting',
            name='expiration_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 8, 12, 10, 17, 9, 702709), null=True),
        ),
        migrations.AlterField(
            model_name='rentlisting',
            name='premium_expiration',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 13, 10, 17, 9, 702734), null=True),
        ),
        migrations.AlterField(
            model_name='salelisting',
            name='expiration_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 5, 14, 10, 17, 9, 700703), null=True),
        ),
        migrations.AlterField(
            model_name='salelisting',
            name='premium_expiration',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 13, 10, 17, 9, 700735), null=True),
        ),
    ]
