# Generated by Django 3.1.6 on 2021-05-17 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0044_auto_20210517_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentlisting',
            name='expiration_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rentlisting',
            name='premium_expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salelisting',
            name='expiration_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salelisting',
            name='premium_expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
