# Generated by Django 3.1.6 on 2021-05-17 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0045_auto_20210517_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentlisting',
            name='times_saved',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='salelisting',
            name='times_saved',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
