# Generated by Django 3.1.6 on 2021-05-17 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0046_auto_20210517_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentlisting',
            name='times_saved',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='salelisting',
            name='times_saved',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
