# Generated by Django 3.1.6 on 2021-05-24 14:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_userprofile_address'),
        ('listings', '0048_salelisting_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='salelisting',
            name='date_sold',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salelisting',
            name='price_sold',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='SoldListing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_number', models.CharField(editable=False, max_length=32, null=True)),
                ('county', models.CharField(max_length=256)),
                ('area', models.CharField(max_length=256)),
                ('eircode', models.CharField(blank=True, max_length=256, null=True)),
                ('property_type', models.CharField(max_length=256)),
                ('price', models.PositiveIntegerField()),
                ('no_of_bedrooms', models.PositiveIntegerField()),
                ('no_of_bathrooms', models.PositiveIntegerField()),
                ('floor_area', models.DecimalField(decimal_places=2, max_digits=10)),
                ('floor_area_type', models.CharField(blank=True, default='Square Meters', max_length=256)),
                ('ber_rating', models.CharField(max_length=256)),
                ('date_sold', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_profile', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.userprofile')),
            ],
        ),
    ]
