# Generated by Django 3.1.6 on 2021-05-26 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0049_auto_20210524_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentlisting',
            name='sold',
            field=models.BooleanField(default=False),
        ),
    ]
