# Generated by Django 3.1.6 on 2021-03-04 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0020_rentlistingimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(editable=False, max_length=32)),
                ('full_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=32)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('order_total', models.IntegerField(default=0)),
                ('stripe_pid', models.CharField(default='', max_length=254)),
                ('rent_listing', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='listings.rentlisting')),
                ('sale_listing', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='listings.salelisting')),
            ],
        ),
    ]
