# Generated by Django 3.1.6 on 2021-03-10 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0021_test'),
        ('checkout', '0002_order_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='rent_listing',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='listings.rentlisting'),
        ),
        migrations.AlterField(
            model_name='order',
            name='sale_listing',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='listings.salelisting'),
        ),
    ]
