# Generated by Django 3.1.6 on 2021-04-13 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_friendly_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pre_sale_price',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
